name: Build (Nintendo Wii)

on: [push, pull_request, workflow_dispatch]

jobs:

  build-wii:
    name: Build (Nintendo Wii)
    runs-on: ubuntu-latest
    container: devkitpro/devkitppc:latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      with:
        submodules: recursive
    
    - name: Install devkit packages
      run: |
        dkp-pacman -Syu --noconfirm
        dkp-pacman -S --needed --noconfirm wii-sdl2 wii-sdl2_image
    
    - name: Create build directory
      run: mkdir -p build
    
    - name: Configure with CMake
      run: /opt/devkitpro/portlibs/wii/bin/powerpc-eabi-cmake -S. -B build
    
    - name: Build
      run: /opt/devkitpro/portlibs/wii/bin/powerpc-eabi-cmake --build build
    
    - name: Prepare structure
      run: |
        mkdir -p pkg/wii/apps/miniCDi
        mkdir -p pkg/wii/apps/miniCDi/rom
        cp ./build/miniCDi.dol ./pkg/wii/apps/miniCDi/boot.dol
        cp ./res/wii/icon.png ./pkg/wii/apps/miniCDi/icon.png
        cp ./build/res/wii/meta.xml ./pkg/wii/apps/miniCDi/meta.xml
    
    - name: Upload artifact
      uses: actions/upload-artifact@v7
      with:
        name: miniCDi
        path: ./pkg/wii/