name: Build (Nintendo Wii)

on:
  push:
    branches: [ "master" ]
    paths:
      - src/**
  pull_request:
    branches: [ "master" ]
    paths:
      - src/**
  workflow_dispatch:
    branches: [ "master" ]

jobs:

  build-wii:
    name: Build (Nintendo Wii)
    runs-on: ubuntu-latest
    container: ghcr.io/extremscorner/libogc2:latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      with:
        submodules: recursive
    
    - name: Install dependencies
      run: |
        for i in {1..3}; do
          echo "Syncing package databases (attempt $i of 3)"
          if dkp-pacman -Syu --noconfirm; then
            break
          else
            sleep 5
          fi
        done
        
        dkp-pacman -S --needed --noconfirm wii-sdl2
    
    - name: Create build directory
      run: mkdir -p build
    
    - name: Configure with CMake
      run: /opt/devkitpro/libogc2/wii/bin/powerpc-eabi-cmake -S. -B build
    
    - name: Build
      run: /opt/devkitpro/libogc2/wii/bin/powerpc-eabi-cmake --build build
    
    - name: Prepare structure
      run: |
        mkdir -p pkg/wii/apps/miniCDi
        mkdir -p pkg/wii/apps/miniCDi/rom
        cp ./build/miniCDi.dol ./pkg/wii/apps/miniCDi/boot.dol
        cp ./res/wii/icon.png ./pkg/wii/apps/miniCDi/icon.png
        cp ./build/res/wii/meta.xml ./pkg/wii/apps/miniCDi/meta.xml
    
    - name: Upload artifact
      uses: actions/upload-artifact@v7
      with:
        name: miniCDi
        path: ./pkg/wii/